export const INTERVIEW_SCENARIOS = [
  {
    name: 'Design a URL Shortener',
    subtitle: 'Hashing, DB Scaling, Caching',
    timeLimit: 2700, // 45 minutes in seconds
    budget: 8000,
    targetTraffic: 10000,
    baseLatency: 30,
    latencyTarget: 50,
    congestionFactor: 0.06,
    sustainSeconds: 10,
    narrative: {
      title: 'Interview: URL Shortener',
      description: "You're interviewing at a tech company. The interviewer asks: \"Design a URL shortening service like bit.ly that handles 100M URLs and 10,000 reads/sec. Walk me through your architecture.\"",
      objective: 'Handle 10,000 RPS with latency under 50ms. No server crashes.',
      hint: 'This is a read-heavy workload. Think about what percentage of requests can be served from cache.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'replica'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 100, y: 250 }, data: { label: 'Users', rps: 0, region: 'default', isInitial: true } },
      { id: 'server-1', type: 'server', position: { x: 400, y: 250 }, data: { label: 'API Server', rps: 0, capacity: 2000, status: 'healthy', isInitial: true } },
      { id: 'db-1', type: 'database', position: { x: 700, y: 250 }, data: { label: 'URL Database', rps: 0, capacity: 3000, status: 'healthy', isInitial: true } },
    ],
    initialEdges: [
      { id: 'e-t-s', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-s-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 10000 && metrics.avgLatency < 50 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.overloadedServers > 0,
    failMessage: 'Your servers crashed under the load!',
    failExplanation: 'The URL shortener needs to handle massive read traffic. Caching is critical since most requests are reads (redirects), not writes (creating URLs).',
    nodeCosts: { server: 400, database: 500, loadBalancer: 400, cache: 500, cdn: 600, replica: 700 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealApproach: 'Load balancer distributing to 3+ API servers. Redis cache in front of the database handles ~90% of reads (URL lookups). Database with read replicas for the remaining 10%. CDN at the edge for the most popular short URLs. Total cost stays under $6,000.',
    idealSolution: {
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'cdn', label: 'CDN', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'API Server', count: 3 },
        { type: 'cache', label: 'Redis Cache', count: 1 },
        { type: 'database', label: 'URL Database', count: 1 },
        { type: 'replica', label: 'Read Replica', count: 1 },
      ],
    },
  },
  {
    name: 'Design a Chat System',
    subtitle: 'Real-Time, Message Queues, Presence',
    timeLimit: 2700,
    budget: 12000,
    targetTraffic: 15000,
    baseLatency: 40,
    latencyTarget: 100,
    congestionFactor: 0.05,
    sustainSeconds: 10,
    narrative: {
      title: 'Interview: Chat System',
      description: "The interviewer asks: \"Design a real-time chat application like Slack that supports 1M concurrent users and guarantees message delivery. How would you architect this?\"",
      objective: 'Handle 15,000 RPS with latency under 100ms. No system downtime.',
      hint: 'Think about separating connection handling from message processing. What happens when a user is offline?',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker', 'replica', 'healthCheck'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 150 }, data: { label: 'Web Users', rps: 0, region: 'default', isInitial: true } },
      { id: 'traffic-2', type: 'trafficSource', position: { x: 50, y: 400 }, data: { label: 'Mobile Users', rps: 0, region: 'default', isInitial: true } },
      { id: 'server-1', type: 'server', position: { x: 400, y: 250 }, data: { label: 'Chat Server', rps: 0, capacity: 3000, status: 'healthy', isInitial: true } },
      { id: 'db-1', type: 'database', position: { x: 700, y: 250 }, data: { label: 'Message DB', rps: 0, capacity: 5000, status: 'healthy', isInitial: true } },
    ],
    initialEdges: [
      { id: 'e-t1-s', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-t2-s', source: 'traffic-2', target: 'server-1', animated: true },
      { id: 'e-s-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 15000 && metrics.avgLatency < 100 && metrics.overloadedServers === 0 && !metrics.systemDown,
    failCondition: (metrics) => metrics.overloadedServers > 0 || metrics.systemDown,
    failMessage: 'The chat system went down!',
    failExplanation: 'A chat system needs to handle bursty traffic from millions of concurrent connections. Message queues decouple sending from delivery, and caching handles presence/status lookups.',
    nodeCosts: { server: 400, database: 500, loadBalancer: 400, cache: 500, messageQueue: 600, worker: 350, replica: 700, healthCheck: 300 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealApproach: 'Load balancer -> connection servers (3+) for WebSocket handling. Message queue buffers messages for async delivery. Workers process the queue and push to recipients. Cache stores user presence (online/offline). Database with replicas persists messages. Health checks detect server failures.',
    idealSolution: {
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 2 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Connection Server', count: 3 },
        { type: 'cache', label: 'Presence Cache', count: 1 },
        { type: 'messageQueue', label: 'Message Queue', count: 1 },
        { type: 'worker', label: 'Delivery Worker', count: 2 },
        { type: 'database', label: 'Message DB', count: 1 },
        { type: 'replica', label: 'Replica', count: 1 },
        { type: 'healthCheck', label: 'Health Check', count: 1 },
      ],
    },
  },
  {
    name: 'Design a Notification Service',
    subtitle: 'Fan-Out, Priority Queues, Rate Limiting',
    timeLimit: 2700,
    budget: 15000,
    targetTraffic: 20000,
    baseLatency: 50,
    latencyTarget: 150,
    congestionFactor: 0.04,
    sustainSeconds: 10,
    narrative: {
      title: 'Interview: Notification Service',
      description: "\"Design a notification service that sends push, email, and SMS to 50M users with different priority levels. High-priority alerts must arrive within seconds.\"",
      objective: 'Handle 20,000 RPS with latency under 150ms.',
      hint: 'Not all notifications are equal. How do you ensure high-priority messages don\'t get stuck behind a backlog of marketing emails?',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker', 'apiGateway', 'autoScaler'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 100, y: 250 }, data: { label: 'API Clients', rps: 0, region: 'default', isInitial: true } },
      { id: 'server-1', type: 'server', position: { x: 400, y: 250 }, data: { label: 'Notification Server', rps: 0, capacity: 4000, status: 'healthy', isInitial: true } },
      { id: 'db-1', type: 'database', position: { x: 700, y: 250 }, data: { label: 'User Prefs DB', rps: 0, capacity: 5000, status: 'healthy', isInitial: true } },
    ],
    initialEdges: [
      { id: 'e-t-s', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-s-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 20000 && metrics.avgLatency < 150 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.overloadedServers > 0,
    failMessage: 'Notifications are backing up and timing out!',
    failExplanation: 'A notification service must handle massive fan-out. Without priority queues and worker pools, high-priority alerts get stuck behind bulk marketing emails.',
    nodeCosts: { server: 400, database: 500, loadBalancer: 400, cache: 500, messageQueue: 600, worker: 350, apiGateway: 800, autoScaler: 1000 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealApproach: 'API Gateway for rate limiting and auth -> load balancer -> intake servers -> priority message queues (high/low) -> auto-scaled worker pools per channel (push, email, SMS). Cache for user notification preferences. Database stores delivery logs.',
    idealSolution: {
      nodes: [
        { type: 'trafficSource', label: 'API Clients', count: 1 },
        { type: 'apiGateway', label: 'API Gateway', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Intake Server', count: 3 },
        { type: 'cache', label: 'Prefs Cache', count: 1 },
        { type: 'messageQueue', label: 'Priority Queue', count: 1 },
        { type: 'worker', label: 'Delivery Worker', count: 3 },
        { type: 'autoScaler', label: 'Auto-Scaler', count: 1 },
        { type: 'database', label: 'User Prefs DB', count: 1 },
      ],
    },
  },
  {
    name: 'Design a Rate Limiter',
    subtitle: 'API Gateway, Distributed Counters, Edge',
    timeLimit: 2700,
    budget: 10000,
    targetTraffic: 50000,
    baseLatency: 15,
    latencyTarget: 30,
    congestionFactor: 0.03,
    sustainSeconds: 10,
    narrative: {
      title: 'Interview: Rate Limiter',
      description: "\"Design a distributed rate limiting service that protects your API from abuse. It needs to handle 50,000 RPS across multiple regions with sub-30ms overhead.\"",
      objective: 'Handle 50,000 RPS with latency under 30ms.',
      hint: 'Rate limiting must be fast — every request passes through it. Where should the counters live? Can you push decisions to the edge?',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'apiGateway', 'circuitBreaker', 'replica'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 100 }, data: { label: 'US Traffic', rps: 0, region: 'us', isInitial: true } },
      { id: 'traffic-2', type: 'trafficSource', position: { x: 50, y: 280 }, data: { label: 'EU Traffic', rps: 0, region: 'eu', isInitial: true } },
      { id: 'traffic-3', type: 'trafficSource', position: { x: 50, y: 460 }, data: { label: 'Asia Traffic', rps: 0, region: 'asia', isInitial: true } },
      { id: 'gw-1', type: 'apiGateway', position: { x: 350, y: 280 }, data: { label: 'API Gateway', rps: 0, status: 'healthy', isInitial: true } },
      { id: 'server-1', type: 'server', position: { x: 650, y: 280 }, data: { label: 'API Server', rps: 0, capacity: 10000, status: 'healthy', isInitial: true } },
    ],
    initialEdges: [
      { id: 'e-t1-gw', source: 'traffic-1', target: 'gw-1', animated: true },
      { id: 'e-t2-gw', source: 'traffic-2', target: 'gw-1', animated: true },
      { id: 'e-t3-gw', source: 'traffic-3', target: 'gw-1', animated: true },
      { id: 'e-gw-s', source: 'gw-1', target: 'server-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 50000 && metrics.avgLatency < 30 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.overloadedServers > 0,
    failMessage: 'The rate limiter is too slow — requests are timing out!',
    failExplanation: 'Rate limiting at 50K RPS requires sub-millisecond counter lookups. A database is too slow. You need in-memory counters (cache/Redis) and edge-level filtering.',
    nodeCosts: { server: 400, database: 500, loadBalancer: 400, cache: 500, cdn: 600, apiGateway: 800, circuitBreaker: 800, replica: 700 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealApproach: 'CDN edges filter obvious abuse at the perimeter. API Gateways per region enforce rate limits using Redis cache for distributed counters. Load balancer spreads traffic across API servers. Circuit breakers protect downstream services. Cache replicas ensure counter consistency across regions.',
    idealSolution: {
      nodes: [
        { type: 'trafficSource', label: 'Regional Traffic', count: 3 },
        { type: 'cdn', label: 'CDN Edge', count: 1 },
        { type: 'apiGateway', label: 'API Gateway', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'API Server', count: 4 },
        { type: 'cache', label: 'Rate Counter Cache', count: 1 },
        { type: 'circuitBreaker', label: 'Circuit Breaker', count: 1 },
        { type: 'replica', label: 'Cache Replica', count: 1 },
      ],
    },
  },
  {
    name: 'Design File Storage',
    subtitle: 'CDN, Chunked Uploads, Replication',
    timeLimit: 2700,
    budget: 18000,
    targetTraffic: 8000,
    baseLatency: 60,
    latencyTarget: 200,
    congestionFactor: 0.05,
    sustainSeconds: 10,
    narrative: {
      title: 'Interview: File Storage',
      description: "\"Design a cloud file storage system like Dropbox that handles 5M files uploaded daily and serves downloads globally with low latency. How do you handle large files?\"",
      objective: 'Handle 8,000 RPS with latency under 200ms. No system downtime.',
      hint: 'Uploads and downloads have very different patterns. Can you separate them? What about large files that take minutes to process?',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'messageQueue', 'worker', 'replica', 'healthCheck', 'autoScaler'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 150 }, data: { label: 'Uploaders', rps: 0, region: 'default', isInitial: true } },
      { id: 'traffic-2', type: 'trafficSource', position: { x: 50, y: 400 }, data: { label: 'Downloaders', rps: 0, region: 'default', isInitial: true } },
      { id: 'server-1', type: 'server', position: { x: 400, y: 250 }, data: { label: 'File Server', rps: 0, capacity: 2000, status: 'healthy', isInitial: true } },
      { id: 'db-1', type: 'database', position: { x: 700, y: 250 }, data: { label: 'Metadata DB', rps: 0, capacity: 5000, status: 'healthy', isInitial: true } },
    ],
    initialEdges: [
      { id: 'e-t1-s', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-t2-s', source: 'traffic-2', target: 'server-1', animated: true },
      { id: 'e-s-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 8000 && metrics.avgLatency < 200 && metrics.overloadedServers === 0 && !metrics.systemDown,
    failCondition: (metrics) => metrics.overloadedServers > 0 || metrics.systemDown,
    failMessage: 'File uploads are failing and downloads are timing out!',
    failExplanation: 'A file storage system needs separate paths for uploads and downloads. Downloads should be served from CDN. Uploads need async processing (virus scan, thumbnails) via message queues and workers.',
    nodeCosts: { server: 400, database: 500, loadBalancer: 400, cache: 500, cdn: 600, messageQueue: 600, worker: 350, replica: 700, healthCheck: 300, autoScaler: 1000 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealApproach: 'CDN serves cached file downloads globally. Load balancer splits traffic to upload servers and download servers. Upload servers push to message queue for async processing (thumbnails, virus scanning). Workers handle the processing. Metadata DB with replicas stores file info. Health checks ensure failover. Auto-scaler adjusts worker count based on upload volume.',
    idealSolution: {
      nodes: [
        { type: 'trafficSource', label: 'Uploaders', count: 1 },
        { type: 'trafficSource', label: 'Downloaders', count: 1 },
        { type: 'cdn', label: 'CDN', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Upload Server', count: 2 },
        { type: 'server', label: 'Download Server', count: 2 },
        { type: 'messageQueue', label: 'Processing Queue', count: 1 },
        { type: 'worker', label: 'File Worker', count: 2 },
        { type: 'cache', label: 'Metadata Cache', count: 1 },
        { type: 'database', label: 'Metadata DB', count: 1 },
        { type: 'replica', label: 'DB Replica', count: 1 },
        { type: 'healthCheck', label: 'Health Check', count: 1 },
      ],
    },
  },
];

export const TOTAL_INTERVIEWS = INTERVIEW_SCENARIOS.length;
