export const LEVEL_CONFIGS = {
  0: {
    name: 'Sandbox',
    subtitle: 'Freeplay Mode',
    budget: 999999,
    initialTraffic: 0,
    targetTraffic: 50000,
    baseLatency: 20,
    congestionFactor: 0.03,
    sustainSeconds: 999,
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'region', 'replica', 'healthCheck', 'apiGateway', 'messageQueue', 'worker', 'autoScaler', 'circuitBreaker'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 100, y: 300 }, data: { label: 'Users', rps: 0, region: 'default' } },
    ],
    initialEdges: [],
    winCondition: () => false,
    failCondition: () => false,
    failMessage: '',
    failExplanation: '',
    winLesson: '',
    narrative: { title: 'Sandbox', description: 'Build whatever you want.', objective: 'No objectives — experiment freely!', hint: 'Try building a full production architecture from scratch.' },
    nodeCosts: { server: 200, database: 300, loadBalancer: 400, cache: 500, cdn: 600, region: 0, replica: 700, healthCheck: 300, apiGateway: 800, messageQueue: 600, worker: 350, autoScaler: 1000, circuitBreaker: 800 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
  },

  1: {
    name: 'The Monolith',
    subtitle: 'Vertical vs. Horizontal Scaling',
    budget: 500,
    initialTraffic: 0,
    targetTraffic: 1000,
    baseLatency: 50,
    congestionFactor: 0.1,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 1: Humble Beginnings',
      description: "You're a solo developer who just launched a product. It's running on a single server — your \"monolith.\" Traffic is starting to pick up, but your server can only handle so much. When it gets overloaded, it crashes.",
      objective: 'Handle 1,000 requests per second without any server crashing.',
      hint: 'Try adding more servers and connecting them to the traffic source.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 100, y: 200 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'server-1', type: 'server', position: { x: 400, y: 200 }, data: { label: 'Web Server', rps: 0, capacity: 500, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 700, y: 200 }, data: { label: 'SQL Database', rps: 0, capacity: 2000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-server', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-server-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 1000 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.overloadedServers > 0;
    },
    failMessage: "Your server caught fire! It can't handle all that traffic alone.",
    failExplanation: 'A single server has limited capacity. When traffic exceeds that limit, it crashes. You need to scale horizontally — add more servers to share the load.',
    winLesson: "You just learned horizontal scaling — adding more machines instead of upgrading one. This is how Netflix, Google, and Amazon handle billions of requests. It's cheaper and more resilient than buying one giant server.",
    references: [
      { title: 'Horizontal vs Vertical Scaling', url: 'https://www.cloudflare.com/learning/performance/what-is-horizontal-scaling/' },
      { title: 'System Design Primer — Scaling', url: 'https://github.com/donnemartin/system-design-primer#scalability' },
    ],
    nodeCosts: { server: 200, database: 300 },
    activeSimulators: ['traffic'],
    idealSolution: {
      description: 'Horizontal scaling with multiple servers',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'server', label: 'Web Server', count: 3 },
        { type: 'database', label: 'SQL Database', count: 1 },
      ],
      explanation: 'Distribute traffic across 3 servers (500 RPS each) instead of overloading one. Total capacity: 1,500 RPS > 1,000 RPS target.',
    },
  },

  2: {
    name: 'The Distribution',
    subtitle: 'Load Balancing',
    budget: 2000,
    initialTraffic: 0,
    targetTraffic: 3000,
    baseLatency: 40,
    congestionFactor: 0.08,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 2: The Distribution',
      description: "Your app is growing! You now have 3 servers, but there's a problem — all traffic is going to Server 1 while Servers 2 and 3 sit idle. You need something to distribute the load evenly.",
      objective: 'Handle 3,000 RPS by distributing traffic evenly across all servers.',
      hint: 'Place a Load Balancer between the traffic source and your servers.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 250 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'server-1', type: 'server', position: { x: 500, y: 100 }, data: { label: 'Server 1', rps: 0, capacity: 1200, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 500, y: 280 }, data: { label: 'Server 2', rps: 0, capacity: 1200, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 500, y: 460 }, data: { label: 'Server 3', rps: 0, capacity: 1200, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 800, y: 250 }, data: { label: 'SQL Database', rps: 0, capacity: 5000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-s1', source: 'traffic-1', target: 'server-1', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
      { id: 'e-s2-db', source: 'server-2', target: 'db-1', animated: true },
      { id: 'e-s3-db', source: 'server-3', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 3000 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.overloadedServers > 0;
    },
    failMessage: 'Server 1 is overwhelmed while other servers sit idle!',
    failExplanation: "Without a load balancer, all traffic hits a single server. The others can't help because nothing is routing requests to them. A load balancer acts as a traffic cop, distributing requests evenly.",
    winLesson: "Load balancers distribute traffic evenly — this is how every major website works. Even the simplest algorithm (round-robin) is a massive improvement over sending everything to one server.",
    references: [
      { title: 'What is Load Balancing?', url: 'https://www.nginx.com/resources/glossary/load-balancing/' },
      { title: 'Load Balancing Algorithms', url: 'https://samwho.dev/load-balancing/' },
    ],
    nodeCosts: { server: 300, loadBalancer: 400, database: 300 },
    activeSimulators: ['traffic', 'loadBalancer'],
    idealSolution: {
      description: 'Load balancer distributing to all servers',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Web Server', count: 3 },
        { type: 'database', label: 'SQL Database', count: 1 },
      ],
      explanation: 'A load balancer routes traffic evenly across all 3 servers. Without it, only the directly-connected server gets traffic.',
    },
  },

  3: {
    name: 'The Speed Demon',
    subtitle: 'Caching',
    budget: 3000,
    initialTraffic: 0,
    targetTraffic: 5000,
    baseLatency: 40,
    congestionFactor: 0.06,
    sustainSeconds: 10,
    latencyTarget: 100,
    narrative: {
      title: 'Chapter 3: The Speed Demon',
      description: "Traffic keeps growing. Your load-balanced servers handle the throughput fine, but the database is becoming a bottleneck. Every request hits the database, and response times are creeping up. Users are starting to notice the lag.",
      objective: 'Handle 5,000 RPS while keeping latency below 100ms.',
      hint: 'Add a Cache between your servers and the database to serve repeated queries from memory.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 250 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 250, y: 250 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 480, y: 100 }, data: { label: 'Server 1', rps: 0, capacity: 2000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 480, y: 280 }, data: { label: 'Server 2', rps: 0, capacity: 2000, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 480, y: 460 }, data: { label: 'Server 3', rps: 0, capacity: 2000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 800, y: 250 }, data: { label: 'SQL Database', rps: 0, capacity: 3000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-lb-s3', source: 'lb-1', target: 'server-3', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
      { id: 'e-s2-db', source: 'server-2', target: 'db-1', animated: true },
      { id: 'e-s3-db', source: 'server-3', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 5000 && metrics.avgLatency < 100 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.avgLatency >= 200;
    },
    failMessage: 'Latency is through the roof! Your database is doing a full table scan for every single request.',
    failExplanation: 'Without caching, every request goes to the database. Databases are great for storage but slow for repeated reads. A cache stores frequent results in memory, dramatically reducing response times.',
    winLesson: "Caching stores frequent results in memory — Redis handles millions of reads per second. Most real applications cache 80-95% of their reads. This is why Twitter, Instagram, and Facebook feel instant.",
    references: [
      { title: 'Caching Strategies', url: 'https://aws.amazon.com/caching/best-practices/' },
      { title: 'Redis Documentation', url: 'https://redis.io/docs/latest/develop/get-started/' },
    ],
    nodeCosts: { server: 300, loadBalancer: 400, database: 300, cache: 500 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealSolution: {
      description: 'Cache layer between servers and database',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Web Server', count: 3 },
        { type: 'cache', label: 'Redis Cache', count: 1 },
        { type: 'database', label: 'SQL Database', count: 1 },
      ],
      explanation: 'A cache absorbs ~80% of read traffic, keeping the database under its 3,000 QPS limit and reducing latency from ~40ms to ~5ms for cached queries.',
    },
  },

  4: {
    name: 'The Global Expansion',
    subtitle: 'CDNs & Regions',
    budget: 5000,
    initialTraffic: 0,
    targetTraffic: 8000,
    baseLatency: 30,
    congestionFactor: 0.04,
    sustainSeconds: 10,
    latencyTarget: 200,
    narrative: {
      title: 'Chapter 4: The Global Expansion',
      description: "Your app has gone viral internationally! But there's a problem — all your infrastructure is in India. Users in the US and Europe are experiencing 300ms+ latency, and they're bouncing off your site.",
      objective: 'Handle 8,000 RPS from 3 regions with under 200ms latency everywhere.',
      hint: 'Deploy a CDN and consider adding servers in regions closer to your users.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'region'],
    regions: [
      { id: 'region-india', name: 'India', latencyFromOthers: { 'region-us': 250, 'region-europe': 180 } },
      { id: 'region-us', name: 'US', latencyFromOthers: { 'region-india': 250, 'region-europe': 120 } },
      { id: 'region-europe', name: 'Europe', latencyFromOthers: { 'region-india': 180, 'region-us': 120 } },
    ],
    initialNodes: [
      { id: 'traffic-india', type: 'trafficSource', position: { x: 50, y: 200 }, data: { label: 'India Users', rps: 0, region: 'region-india' } },
      { id: 'traffic-us', type: 'trafficSource', position: { x: 50, y: 450 }, data: { label: 'US Users', rps: 0, region: 'region-us' } },
      { id: 'traffic-europe', type: 'trafficSource', position: { x: 50, y: 700 }, data: { label: 'Europe Users', rps: 0, region: 'region-europe' } },
      { id: 'region-india', type: 'region', position: { x: 300, y: 50 }, data: { label: 'India Region', region: 'region-india' }, style: { width: 900, height: 380 } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 30, y: 140 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' }, parentNode: 'region-india', extent: 'parent' },
      { id: 'server-1', type: 'server', position: { x: 260, y: 60 }, data: { label: 'Server 1', rps: 0, capacity: 3000, status: 'healthy' }, parentNode: 'region-india', extent: 'parent' },
      { id: 'server-2', type: 'server', position: { x: 260, y: 230 }, data: { label: 'Server 2', rps: 0, capacity: 3000, status: 'healthy' }, parentNode: 'region-india', extent: 'parent' },
      { id: 'cache-1', type: 'cache', position: { x: 500, y: 140 }, data: { label: 'Redis Cache', rps: 0, hitRate: 0, status: 'healthy' }, parentNode: 'region-india', extent: 'parent' },
      { id: 'db-1', type: 'database', position: { x: 700, y: 140 }, data: { label: 'SQL Database', rps: 0, capacity: 5000, status: 'healthy' }, parentNode: 'region-india', extent: 'parent' },
    ],
    initialEdges: [
      { id: 'e-ti-lb', source: 'traffic-india', target: 'lb-1', animated: true },
      { id: 'e-tu-lb', source: 'traffic-us', target: 'lb-1', animated: true },
      { id: 'e-te-lb', source: 'traffic-europe', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 8000 && metrics.maxRegionLatency < 200 && metrics.bouncedUsers === 0;
    },
    failCondition: (metrics) => {
      return metrics.bouncedUsers > 100;
    },
    failMessage: "Users are leaving! Visitors from distant regions can't stand the lag.",
    failExplanation: "When all your servers are in one location, distant users experience high latency due to the physical distance data must travel. CDNs cache content at edge locations worldwide, and multi-region deployment puts your servers closer to users.",
    winLesson: "CDNs and multi-region deployment reduce latency by serving users from nearby locations. This is how Cloudflare, AWS CloudFront, and Akamai make the web fast — by putting copies of your content everywhere.",
    references: [
      { title: 'What is a CDN?', url: 'https://www.cloudflare.com/learning/cdn/what-is-a-cdn/' },
      { title: 'Multi-Site Active/Active on AWS', url: 'https://aws.amazon.com/blogs/architecture/disaster-recovery-dr-architecture-on-aws-part-iv-multi-site-active-active/' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, cdn: 600, region: 0 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache', 'geoLatency'],
    idealSolution: {
      description: 'Multi-region with CDN edge caching',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 3 },
        { type: 'cdn', label: 'CDN', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 4 },
        { type: 'cache', label: 'Cache', count: 1 },
        { type: 'database', label: 'Database', count: 1 },
      ],
      explanation: 'CDN serves static content from edge locations close to each region, reducing cross-region latency. Servers and cache handle dynamic requests.',
    },
  },

  5: {
    name: 'The Unstoppable App',
    subtitle: 'Fault Tolerance',
    budget: 8000,
    initialTraffic: 0,
    targetTraffic: 10000,
    baseLatency: 30,
    congestionFactor: 0.03,
    sustainSeconds: 10,
    disasterTime: 15,
    narrative: {
      title: 'Chapter 5: The Unstoppable App',
      description: "You're now running a global platform. Everything seems perfect until — disaster strikes. A data center goes offline. Your primary database fails. Can your system survive?",
      objective: 'Survive a data center failure while maintaining over 50% RPS capacity.',
      hint: 'Set up database replicas for redundancy and health checks to detect failures automatically.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'region', 'replica', 'healthCheck'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 300 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'cdn-1', type: 'cdn', position: { x: 220, y: 300 }, data: { label: 'CDN', rps: 0, cacheRate: 0.3, status: 'healthy' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 420, y: 300 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 640, y: 150 }, data: { label: 'Server 1', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 640, y: 320 }, data: { label: 'Server 2', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 640, y: 490 }, data: { label: 'Server 3', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'cache-1', type: 'cache', position: { x: 860, y: 230 }, data: { label: 'Redis Cache', rps: 0, hitRate: 0, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 1060, y: 300 }, data: { label: 'Primary DB', rps: 0, capacity: 5000, status: 'healthy', isPrimary: true } },
    ],
    initialEdges: [
      { id: 'e-traffic-cdn', source: 'traffic-1', target: 'cdn-1', animated: true },
      { id: 'e-cdn-lb', source: 'cdn-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-lb-s3', source: 'lb-1', target: 'server-3', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-s3-cache', source: 'server-3', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.survivedDisaster && metrics.rps >= 5000;
    },
    failCondition: (metrics) => {
      return metrics.systemDown;
    },
    failMessage: 'SYSTEM DOWN. Total blackout.',
    failExplanation: 'When your primary database fails and there are no replicas, everything stops. Database replication creates copies that can take over instantly. Health checks detect failures so traffic can be rerouted automatically.',
    winLesson: "Replication and health checks give you high availability — no single point of failure. This is how AWS achieves 99.99% uptime. Every production system at scale uses redundancy and automated failover.",
    references: [
      { title: 'Database Replication', url: 'https://www.postgresql.org/docs/current/high-availability.html' },
      { title: 'High Availability Patterns', url: 'https://learn.microsoft.com/en-us/azure/architecture/checklist/resiliency-per-service' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, cdn: 600, replica: 700, healthCheck: 300, region: 0 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache', 'failover'],
    idealSolution: {
      description: 'Replicas and health checks for fault tolerance',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 3 },
        { type: 'cache', label: 'Cache', count: 1 },
        { type: 'database', label: 'Primary DB', count: 1 },
        { type: 'replica', label: 'Replica DB', count: 1 },
        { type: 'healthCheck', label: 'Health Check', count: 1 },
      ],
      explanation: 'A replica takes over when the primary DB fails. Health checks detect the failure and trigger automatic failover, preventing system-wide outage.',
    },
  },
  6: {
    name: 'The Gatekeeper',
    subtitle: 'Rate Limiting & API Gateway',
    budget: 6000,
    initialTraffic: 0,
    targetTraffic: 12000,
    baseLatency: 30,
    congestionFactor: 0.04,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 6: The Gatekeeper',
      description: "Your platform is under attack! Bots and scrapers are consuming 40% of your server capacity, causing legitimate users to experience slow responses. You need to filter the bad traffic before it reaches your servers.",
      objective: 'Handle 12,000 legitimate RPS by blocking bot traffic with an API Gateway.',
      hint: 'Place an API Gateway before the load balancer. It will rate-limit incoming traffic and block the excess.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'apiGateway'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 250 }, data: { label: 'Users + Bots', rps: 0, region: 'default', botPercent: 0.4 } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 400, y: 250 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 650, y: 100 }, data: { label: 'Server 1', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 650, y: 250 }, data: { label: 'Server 2', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 650, y: 400 }, data: { label: 'Server 3', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'cache-1', type: 'cache', position: { x: 880, y: 250 }, data: { label: 'Redis Cache', rps: 0, hitRate: 0, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 1080, y: 250 }, data: { label: 'SQL Database', rps: 0, capacity: 5000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-lb-s3', source: 'lb-1', target: 'server-3', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-s3-cache', source: 'server-3', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 12000 && metrics.overloadedServers === 0 && metrics.totalBlocked > 0;
    },
    failCondition: (metrics) => {
      return metrics.overloadedServers > 0;
    },
    failMessage: 'Servers overloaded! Bot traffic is eating your capacity.',
    failExplanation: 'Without an API Gateway to filter traffic, bots consume the same resources as real users. Rate limiting blocks abusive traffic before it reaches your servers.',
    winLesson: "API Gateways are the front door to your system. Rate limiting protects backend services from abuse and DDoS attacks. This is how Cloudflare, AWS API Gateway, and Kong work in production.",
    references: [
      { title: 'API Gateway Pattern', url: 'https://microservices.io/patterns/apigateway.html' },
      { title: 'Rate Limiting Strategies', url: 'https://www.cloudflare.com/learning/bots/what-is-rate-limiting/' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, apiGateway: 800 },
    activeSimulators: ['traffic', 'rateLimiter', 'loadBalancer', 'cache'],
    idealSolution: {
      description: 'API Gateway for rate limiting and traffic filtering',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'apiGateway', label: 'API Gateway', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 4 },
        { type: 'cache', label: 'Cache', count: 1 },
        { type: 'database', label: 'Database', count: 1 },
      ],
      explanation: 'The API Gateway filters malicious traffic and rate-limits requests before they reach your servers, preventing overload from bots and abuse.',
    },
  },

  7: {
    name: 'The Decoupler',
    subtitle: 'Message Queues & Async Processing',
    budget: 7000,
    initialTraffic: 0,
    targetTraffic: 10000,
    baseLatency: 30,
    congestionFactor: 0.05,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 7: The Decoupler',
      description: "Your app has a payment processing feature that takes 2-5 seconds per transaction. When traffic spikes, synchronous payment calls block your web servers and create massive latency for ALL users — even those just browsing.",
      objective: 'Handle 10,000 RPS while keeping latency below 150ms by offloading slow work to a queue.',
      hint: 'Add a Message Queue between servers and Worker nodes. Workers process payments asynchronously without blocking the web servers.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'apiGateway', 'messageQueue', 'worker'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 250 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 250, y: 250 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 480, y: 130 }, data: { label: 'Server 1', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 480, y: 300 }, data: { label: 'Server 2', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 480, y: 470 }, data: { label: 'Server 3', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 900, y: 250 }, data: { label: 'SQL Database', rps: 0, capacity: 4000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-lb-s3', source: 'lb-1', target: 'server-3', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
      { id: 'e-s2-db', source: 'server-2', target: 'db-1', animated: true },
      { id: 'e-s3-db', source: 'server-3', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 10000 && metrics.avgLatency < 150 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.avgLatency >= 500;
    },
    failMessage: 'Latency explosion! Synchronous payment processing is blocking everything.',
    failExplanation: 'Without a message queue, slow operations (like payment processing) block web servers from handling new requests. A queue decouples fast web servers from slow background work.',
    winLesson: "Message queues decouple fast web servers from slow background jobs. This is how every e-commerce site handles payments, emails, and notifications — asynchronously, without blocking users.",
    references: [
      { title: 'Message Queue Fundamentals', url: 'https://aws.amazon.com/message-queue/' },
      { title: 'RabbitMQ vs Kafka', url: 'https://aws.amazon.com/compare/the-difference-between-rabbitmq-and-kafka/' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, messageQueue: 600, worker: 350 },
    activeSimulators: ['traffic', 'loadBalancer', 'queue'],
    idealSolution: {
      description: 'Message queue with workers for async processing',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 3 },
        { type: 'messageQueue', label: 'Message Queue', count: 1 },
        { type: 'worker', label: 'Worker', count: 3 },
        { type: 'database', label: 'Database', count: 1 },
      ],
      explanation: 'Servers push heavy tasks to the message queue. Workers process them asynchronously, decoupling request handling from background work.',
    },
  },

  8: {
    name: 'The Split',
    subtitle: 'Microservices & Service Mesh',
    budget: 10000,
    initialTraffic: 0,
    targetTraffic: 15000,
    baseLatency: 25,
    congestionFactor: 0.03,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 8: The Split',
      description: "Your monolithic app is getting harder to scale. The user profile service needs 10x more capacity than the product catalog, but they're stuck in the same server. Splitting into microservices lets you scale each part independently.",
      objective: 'Handle 15,000 RPS across independent services with latency under 100ms.',
      hint: 'Break the monolith into separate server clusters for each concern. A Service Mesh reduces inter-service latency.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 300 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 250, y: 300 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 500, y: 300 }, data: { label: 'Monolith', rps: 0, capacity: 5000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 750, y: 300 }, data: { label: 'SQL Database', rps: 0, capacity: 4000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 15000 && metrics.avgLatency < 100 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.overloadedServers > 1;
    },
    failMessage: 'The monolith can\'t scale! One service is bottlenecking the entire system.',
    failExplanation: 'A monolithic architecture forces all services to scale together. When one component needs more resources, everything must scale up. Microservices let you scale each part independently.',
    winLesson: "Microservices let you scale and deploy each part of your system independently. This is how Netflix, Uber, and Amazon build at scale — hundreds of small services instead of one giant application.",
    references: [
      { title: 'Microservices Architecture', url: 'https://microservices.io/patterns/microservices.html' },
      { title: 'Martin Fowler on Microservices', url: 'https://martinfowler.com/articles/microservices.html' },
    ],
    nodeCosts: { server: 300, loadBalancer: 400, database: 500, cache: 500, messageQueue: 600, worker: 350 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealSolution: {
      description: 'Microservices with dedicated databases',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'apiGateway', label: 'API Gateway', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 2 },
        { type: 'server', label: 'Service', count: 6 },
        { type: 'messageQueue', label: 'Message Queue', count: 1 },
        { type: 'database', label: 'Database', count: 2 },
        { type: 'cache', label: 'Cache', count: 1 },
      ],
      explanation: 'Each microservice owns its data and scales independently. API Gateway routes to the right service. Message queue handles inter-service communication.',
    },
  },

  9: {
    name: 'The Elastic Cloud',
    subtitle: 'Auto-Scaling',
    budget: 8000,
    initialTraffic: 0,
    targetTraffic: 12000,
    baseLatency: 25,
    congestionFactor: 0.04,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 9: The Elastic Cloud',
      description: "Your traffic follows a wild pattern — massive spikes during the day, quiet at night. Running peak-capacity servers 24/7 wastes money. You need your infrastructure to scale automatically with demand.",
      objective: 'Survive a traffic surge to 12,000 RPS using auto-scaling without any server overloading.',
      hint: 'Attach an Auto-Scaler to your server cluster. It will automatically add capacity when load increases and remove it when load drops.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'autoScaler'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 250 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 280, y: 250 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 530, y: 150 }, data: { label: 'Server 1', rps: 0, capacity: 2000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 530, y: 350 }, data: { label: 'Server 2', rps: 0, capacity: 2000, status: 'healthy' } },
      { id: 'cache-1', type: 'cache', position: { x: 780, y: 250 }, data: { label: 'Redis Cache', rps: 0, hitRate: 0, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 1000, y: 250 }, data: { label: 'SQL Database', rps: 0, capacity: 8000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-traffic-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 12000 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics) => {
      return metrics.overloadedServers > 0;
    },
    failMessage: 'Servers crushed under the traffic spike! No auto-scaling in place.',
    failExplanation: 'Fixed server capacity can\'t handle traffic surges. Auto-scaling monitors load and automatically adds or removes servers to match demand, keeping costs low during quiet periods and capacity high during spikes.',
    winLesson: "Auto-scaling is how cloud providers like AWS EC2, Google Cloud Run, and Azure handle variable load — you only pay for what you use, and capacity matches demand automatically.",
    references: [
      { title: 'AWS Auto Scaling', url: 'https://aws.amazon.com/autoscaling/' },
      { title: 'Scaling Strategies', url: 'https://learn.microsoft.com/en-us/azure/architecture/best-practices/auto-scaling' },
    ],
    nodeCosts: { server: 300, loadBalancer: 400, database: 500, cache: 500, autoScaler: 1000 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache', 'autoScaler'],
    idealSolution: {
      description: 'Auto-scaler responding to traffic spikes',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 3 },
        { type: 'autoScaler', label: 'Auto-Scaler', count: 1 },
        { type: 'cache', label: 'Cache', count: 1 },
        { type: 'database', label: 'Database', count: 1 },
        { type: 'replica', label: 'Replica', count: 1 },
      ],
      explanation: 'The auto-scaler monitors load and spins up new servers automatically when traffic exceeds capacity, then scales down when traffic drops.',
    },
  },

  10: {
    name: 'Chaos Engineering',
    subtitle: 'Fault Injection & Circuit Breakers',
    budget: 12000,
    initialTraffic: 0,
    targetTraffic: 10000,
    baseLatency: 25,
    congestionFactor: 0.03,
    sustainSeconds: 10,
    narrative: {
      title: 'Chapter 10: Chaos Engineering',
      description: "Welcome to the big leagues. You're running a globally distributed system and things WILL break — randomly, unexpectedly. Servers crash. Latency spikes. Traffic surges. Can your architecture survive chaos?",
      objective: 'Survive 5 random chaos events while keeping RPS above 5,000.',
      hint: 'Add Circuit Breakers to prevent cascading failures. Add Replicas and Health Checks for redundancy. Build for failure, not just for success.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'replica', 'healthCheck', 'circuitBreaker'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 300 }, data: { label: 'Users', rps: 0, region: 'default' } },
      { id: 'cdn-1', type: 'cdn', position: { x: 220, y: 300 }, data: { label: 'CDN', rps: 0, cacheRate: 0.3, status: 'healthy' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 420, y: 300 }, data: { label: 'Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 650, y: 150 }, data: { label: 'Server 1', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 650, y: 300 }, data: { label: 'Server 2', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'server-3', type: 'server', position: { x: 650, y: 450 }, data: { label: 'Server 3', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'cache-1', type: 'cache', position: { x: 880, y: 300 }, data: { label: 'Redis Cache', rps: 0, hitRate: 0, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 1100, y: 300 }, data: { label: 'Primary DB', rps: 0, capacity: 5000, status: 'healthy', isPrimary: true } },
    ],
    initialEdges: [
      { id: 'e-traffic-cdn', source: 'traffic-1', target: 'cdn-1', animated: true },
      { id: 'e-cdn-lb', source: 'cdn-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-lb-s3', source: 'lb-1', target: 'server-3', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-s3-cache', source: 'server-3', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => {
      return metrics.rps >= 5000 && metrics.overloadedServers === 0;
    },
    failCondition: (metrics, tickCount) => {
      if (tickCount > 30 && metrics.systemDown) return true;
      if (tickCount > 40 && metrics.rps < 2000) return true;
      return false;
    },
    failMessage: 'Cascading failure! One broken component took down your entire system.',
    failExplanation: 'Without circuit breakers and redundancy, a single failure cascades through your architecture. Circuit breakers isolate failures. Replicas and health checks provide automatic recovery.',
    winLesson: "Chaos engineering (pioneered by Netflix's Chaos Monkey) proves your system's resilience before failures happen in production. Circuit breakers prevent one slow service from taking down your entire app.",
    references: [
      { title: 'Netflix Chaos Monkey', url: 'https://netflix.github.io/chaosmonkey/' },
      { title: 'Circuit Breaker Pattern', url: 'https://martinfowler.com/bliki/CircuitBreaker.html' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, cdn: 600, replica: 700, healthCheck: 300, circuitBreaker: 800 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache', 'chaos'],
    idealSolution: {
      description: 'Circuit breakers isolating failing services',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Server', count: 3 },
        { type: 'circuitBreaker', label: 'Circuit Breaker', count: 1 },
        { type: 'database', label: 'Database', count: 1 },
        { type: 'replica', label: 'Replica', count: 1 },
        { type: 'healthCheck', label: 'Health Check', count: 1 },
      ],
      explanation: 'Circuit breakers detect when a downstream service fails and stop sending it traffic, preventing cascading failures across the entire system.',
    },
  },

  // === REAL-WORLD SCENARIOS ===

  11: {
    name: "Build Twitter's Feed",
    subtitle: 'Scenario: Fan-Out & Timeline Caching',
    budget: 10000,
    initialTraffic: 0,
    targetTraffic: 20000,
    baseLatency: 20,
    congestionFactor: 0.03,
    sustainSeconds: 12,
    latencyTarget: 100,
    narrative: {
      title: "Scenario: Build Twitter's Feed",
      description: "You're building a social media timeline. Every time someone posts, it fans out to thousands of followers. The read-to-write ratio is 100:1 — people read timelines far more than they post. Your database is drowning in read queries.",
      objective: 'Serve 20,000 RPS of timeline reads with latency under 100ms.',
      hint: 'Cache the pre-computed timelines. A CDN serves static assets. Multiple cache layers drastically reduce database reads.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'messageQueue', 'worker'],
    initialNodes: [
      { id: 'traffic-read', type: 'trafficSource', position: { x: 50, y: 200 }, data: { label: 'Timeline Readers', rps: 0, region: 'default' } },
      { id: 'traffic-write', type: 'trafficSource', position: { x: 50, y: 500 }, data: { label: 'Tweet Writers', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 300, y: 200 }, data: { label: 'Read LB', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-read-1', type: 'server', position: { x: 550, y: 100 }, data: { label: 'Read API 1', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-read-2', type: 'server', position: { x: 550, y: 300 }, data: { label: 'Read API 2', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-write-1', type: 'server', position: { x: 300, y: 500 }, data: { label: 'Write API', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 800, y: 350 }, data: { label: 'Timeline DB', rps: 0, capacity: 5000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-tr-lb', source: 'traffic-read', target: 'lb-1', animated: true },
      { id: 'e-lb-r1', source: 'lb-1', target: 'server-read-1', animated: true },
      { id: 'e-lb-r2', source: 'lb-1', target: 'server-read-2', animated: true },
      { id: 'e-tw-w1', source: 'traffic-write', target: 'server-write-1', animated: true },
      { id: 'e-r1-db', source: 'server-read-1', target: 'db-1', animated: true },
      { id: 'e-r2-db', source: 'server-read-2', target: 'db-1', animated: true },
      { id: 'e-w1-db', source: 'server-write-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 20000 && metrics.avgLatency < 100 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.avgLatency >= 300,
    failMessage: 'Timeline feeds are taking forever to load! Users are leaving.',
    failExplanation: 'Without caching, every timeline read hits the database. With a 100:1 read-write ratio, the DB becomes a massive bottleneck. Twitter solved this by pre-computing timelines into a cache (fanout on write).',
    winLesson: "Twitter serves 500M+ tweets per day using a fan-out-on-write model — when someone tweets, it's pushed into followers' pre-computed timeline caches. Reads never touch the database. This is why your feed loads instantly.",
    references: [
      { title: 'Twitter Architecture: 150M Users & 300K QPS', url: 'https://highscalability.com/the-architecture-twitter-uses-to-deal-with-150m-active-users/' },
      { title: 'Fan-Out Pattern Explained', url: 'https://www.youtube.com/watch?v=QmX2NPkJTKg' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, cdn: 600, messageQueue: 600, worker: 350 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache'],
    idealSolution: {
      description: 'Fan-out with timeline caching',
      nodes: [
        { type: 'trafficSource', label: 'Users', count: 2 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Read Server', count: 3 },
        { type: 'server', label: 'Write Server', count: 1 },
        { type: 'cache', label: 'Timeline Cache', count: 1 },
        { type: 'messageQueue', label: 'Fan-Out Queue', count: 1 },
        { type: 'worker', label: 'Fan-Out Worker', count: 2 },
        { type: 'database', label: 'Database', count: 1 },
      ],
      explanation: 'Pre-compute timelines on write (fan-out-on-write). Cache serves reads instantly. Message queue + workers handle the fan-out asynchronously.',
    },
  },

  12: {
    name: "Scale Uber's Matching",
    subtitle: 'Scenario: Real-Time Geo Matching',
    budget: 12000,
    initialTraffic: 0,
    targetTraffic: 15000,
    baseLatency: 25,
    congestionFactor: 0.04,
    sustainSeconds: 12,
    latencyTarget: 150,
    narrative: {
      title: "Scenario: Scale Uber's Matching",
      description: "You're building a ride-matching system. Riders request rides, drivers send location updates every 4 seconds. The matching engine must pair riders with nearby drivers in real-time. At peak hours, thousands of match requests flood in simultaneously.",
      objective: 'Handle 15,000 RPS of location updates + match requests with latency under 150ms.',
      hint: 'Separate the location ingestion (high-write) from the matching engine (high-compute). Use a message queue to buffer match requests.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker', 'apiGateway'],
    initialNodes: [
      { id: 'traffic-rider', type: 'trafficSource', position: { x: 50, y: 150 }, data: { label: 'Rider Requests', rps: 0, region: 'default' } },
      { id: 'traffic-driver', type: 'trafficSource', position: { x: 50, y: 450 }, data: { label: 'Driver Pings', rps: 0, region: 'default' } },
      { id: 'gw-1', type: 'apiGateway', position: { x: 280, y: 300 }, data: { label: 'API Gateway', rps: 0, rateLimit: 20000, blocked: 0, status: 'healthy' } },
      { id: 'server-loc', type: 'server', position: { x: 530, y: 450 }, data: { label: 'Location Service', rps: 0, capacity: 8000, status: 'healthy' } },
      { id: 'server-match', type: 'server', position: { x: 530, y: 150 }, data: { label: 'Match Engine', rps: 0, capacity: 3000, status: 'healthy' } },
      { id: 'db-loc', type: 'database', position: { x: 800, y: 450 }, data: { label: 'Location Store', rps: 0, capacity: 10000, status: 'healthy' } },
      { id: 'db-rides', type: 'database', position: { x: 800, y: 150 }, data: { label: 'Rides DB', rps: 0, capacity: 4000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-ri-gw', source: 'traffic-rider', target: 'gw-1', animated: true },
      { id: 'e-dr-gw', source: 'traffic-driver', target: 'gw-1', animated: true },
      { id: 'e-gw-loc', source: 'gw-1', target: 'server-loc', animated: true },
      { id: 'e-gw-match', source: 'gw-1', target: 'server-match', animated: true },
      { id: 'e-loc-db', source: 'server-loc', target: 'db-loc', animated: true },
      { id: 'e-match-db', source: 'server-match', target: 'db-rides', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 15000 && metrics.avgLatency < 150 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.overloadedServers > 0,
    failMessage: "Match engine overloaded! Riders are waiting forever for a ride.",
    failExplanation: "The matching engine can't keep up with peak-hour requests. Uber solved this by separating location ingestion from matching, using queues to buffer and horizontally scaling the match workers.",
    winLesson: "Uber processes millions of location updates per second by separating concerns: a high-throughput location service ingests GPS pings, while independent match workers consume from a queue. This separation lets each service scale independently.",
    references: [
      { title: "Uber's Real-Time Matching Architecture", url: 'https://www.uber.com/en-IN/blog/fulfillment-platform-rearchitecture/' },
      { title: 'Uber H3: Hexagonal Geospatial Indexing', url: 'https://www.youtube.com/watch?v=UILoSqvIM2w' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, messageQueue: 600, worker: 350, apiGateway: 800 },
    activeSimulators: ['traffic', 'rateLimiter', 'loadBalancer', 'queue'],
    idealSolution: {
      description: 'Geo-indexed matching with regional processing',
      nodes: [
        { type: 'trafficSource', label: 'Riders', count: 1 },
        { type: 'trafficSource', label: 'Drivers', count: 1 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Matching Server', count: 3 },
        { type: 'cache', label: 'Location Cache', count: 1 },
        { type: 'messageQueue', label: 'Match Queue', count: 1 },
        { type: 'database', label: 'Database', count: 1 },
      ],
      explanation: 'Cache stores real-time driver locations. Matching servers use geo-indexing to find nearby drivers. Message queue ensures reliable match delivery.',
    },
  },

  13: {
    name: 'Design Netflix Streaming',
    subtitle: 'Scenario: Global CDN & Edge Computing',
    budget: 15000,
    initialTraffic: 0,
    targetTraffic: 25000,
    baseLatency: 30,
    congestionFactor: 0.03,
    sustainSeconds: 12,
    latencyTarget: 200,
    narrative: {
      title: 'Scenario: Design Netflix Streaming',
      description: "You're building a video streaming platform serving users across 3 continents. Video content must be cached at edge locations to avoid routing every request back to the origin. Users in distant regions are experiencing buffering and 500ms+ latency.",
      objective: 'Serve 25,000 RPS globally with under 200ms latency and 0 bounced users.',
      hint: 'Deploy CDNs in each region. Cache metadata aggressively. The origin servers should only handle cache misses and API calls.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'cdn', 'region', 'replica'],
    regions: [
      { id: 'region-us', name: 'US', latencyFromOthers: { 'region-asia': 200, 'region-europe': 120 } },
      { id: 'region-europe', name: 'Europe', latencyFromOthers: { 'region-us': 120, 'region-asia': 250 } },
      { id: 'region-asia', name: 'Asia', latencyFromOthers: { 'region-us': 200, 'region-europe': 250 } },
    ],
    initialNodes: [
      { id: 'traffic-us', type: 'trafficSource', position: { x: 50, y: 150 }, data: { label: 'US Viewers', rps: 0, region: 'region-us' } },
      { id: 'traffic-eu', type: 'trafficSource', position: { x: 50, y: 400 }, data: { label: 'EU Viewers', rps: 0, region: 'region-europe' } },
      { id: 'traffic-asia', type: 'trafficSource', position: { x: 50, y: 650 }, data: { label: 'Asia Viewers', rps: 0, region: 'region-asia' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 350, y: 400 }, data: { label: 'Global LB', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 600, y: 250 }, data: { label: 'Origin API 1', rps: 0, capacity: 5000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 600, y: 550 }, data: { label: 'Origin API 2', rps: 0, capacity: 5000, status: 'healthy' } },
      { id: 'cache-1', type: 'cache', position: { x: 850, y: 400 }, data: { label: 'Metadata Cache', rps: 0, hitRate: 0, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 1100, y: 400 }, data: { label: 'Content DB', rps: 0, capacity: 6000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-us-lb', source: 'traffic-us', target: 'lb-1', animated: true },
      { id: 'e-eu-lb', source: 'traffic-eu', target: 'lb-1', animated: true },
      { id: 'e-asia-lb', source: 'traffic-asia', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-s1-cache', source: 'server-1', target: 'cache-1', animated: true },
      { id: 'e-s2-cache', source: 'server-2', target: 'cache-1', animated: true },
      { id: 'e-cache-db', source: 'cache-1', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 25000 && metrics.maxRegionLatency < 200 && metrics.bouncedUsers === 0,
    failCondition: (metrics) => metrics.bouncedUsers > 50,
    failMessage: 'Viewers in distant regions are buffering! They switched to a competitor.',
    failExplanation: "Without CDN edge nodes, every video request routes to origin servers far away. Netflix solved this by building Open Connect — their own CDN with servers inside ISPs worldwide.",
    winLesson: "Netflix delivers 15% of the world's internet traffic using Open Connect, a custom CDN embedded directly in ISP networks. Content is pre-positioned close to viewers so most requests never leave the local network.",
    references: [
      { title: 'Netflix Open Connect CDN', url: 'https://openconnect.netflix.com/en/' },
      { title: 'How Netflix Serves Billions of Hours', url: 'https://www.youtube.com/watch?v=psQzyFfsUGU' },
    ],
    nodeCosts: { server: 500, loadBalancer: 400, database: 600, cache: 500, cdn: 700, region: 0, replica: 700 },
    activeSimulators: ['traffic', 'loadBalancer', 'cache', 'geoLatency'],
    idealSolution: {
      description: 'Global CDN with edge computing',
      nodes: [
        { type: 'trafficSource', label: 'Viewers', count: 3 },
        { type: 'cdn', label: 'CDN Edge', count: 3 },
        { type: 'loadBalancer', label: 'Origin LB', count: 1 },
        { type: 'server', label: 'Origin Server', count: 2 },
        { type: 'cache', label: 'Metadata Cache', count: 1 },
        { type: 'database', label: 'Content DB', count: 1 },
      ],
      explanation: 'CDN edges cache video segments close to viewers in each region. Origin servers only handle cache misses and metadata. This reduces cross-continent latency.',
    },
  },

  14: {
    name: 'WhatsApp Delivery',
    subtitle: 'Scenario: Guaranteed Message Delivery',
    budget: 10000,
    initialTraffic: 0,
    targetTraffic: 18000,
    baseLatency: 20,
    congestionFactor: 0.03,
    sustainSeconds: 12,
    narrative: {
      title: 'Scenario: WhatsApp Message Delivery',
      description: "You're building a messaging system that guarantees delivery — if a user sends a message, it MUST reach the recipient even if they're offline. Messages are piling up and the synchronous delivery pipeline is buckling under load.",
      objective: 'Process 18,000 messages/sec with 0 overloaded servers and latency under 150ms.',
      hint: 'Use message queues for guaranteed delivery. Workers process the queue and persist to database. Cache for online user presence checks.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker', 'replica'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 300 }, data: { label: 'Message Senders', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 280, y: 300 }, data: { label: 'Connection LB', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 520, y: 150 }, data: { label: 'Chat Server 1', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 520, y: 450 }, data: { label: 'Chat Server 2', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 800, y: 300 }, data: { label: 'Message Store', rps: 0, capacity: 5000, status: 'healthy' } },
    ],
    initialEdges: [
      { id: 'e-t-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
      { id: 'e-s2-db', source: 'server-2', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 18000 && metrics.avgLatency < 150 && metrics.overloadedServers === 0,
    failCondition: (metrics) => metrics.avgLatency >= 400,
    failMessage: "Messages are piling up! Users see 'sending...' forever.",
    failExplanation: "Synchronous writes to the database block the chat servers. WhatsApp solved this with an async queue — messages are queued for guaranteed delivery and processed by workers that persist to the database.",
    winLesson: "WhatsApp handles 100B+ messages per day using Erlang-based servers with async message queuing. Messages are stored temporarily in queues and delivered when recipients come online. This guarantees delivery without blocking senders.",
    references: [
      { title: 'WhatsApp Architecture at Scale', url: 'https://www.youtube.com/watch?v=vvhC64hQZMk' },
      { title: 'Message Delivery Guarantees', url: 'https://www.cloudamqp.com/blog/what-is-message-queuing.html' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, messageQueue: 600, worker: 350, replica: 700 },
    activeSimulators: ['traffic', 'loadBalancer', 'queue', 'cache'],
    idealSolution: {
      description: 'Guaranteed delivery with persistent queues',
      nodes: [
        { type: 'trafficSource', label: 'Senders', count: 2 },
        { type: 'loadBalancer', label: 'Load Balancer', count: 1 },
        { type: 'server', label: 'Connection Server', count: 3 },
        { type: 'messageQueue', label: 'Delivery Queue', count: 1 },
        { type: 'worker', label: 'Delivery Worker', count: 2 },
        { type: 'database', label: 'Message Store', count: 1 },
        { type: 'cache', label: 'Presence Cache', count: 1 },
      ],
      explanation: 'Messages persist in the queue until acknowledged. If recipient is offline, delivery workers retry from the queue. Presence cache tracks who is online.',
    },
  },

  15: {
    name: "Stripe's Payment Pipeline",
    subtitle: 'Scenario: Exactly-Once Processing',
    budget: 12000,
    initialTraffic: 0,
    targetTraffic: 12000,
    baseLatency: 25,
    congestionFactor: 0.04,
    sustainSeconds: 12,
    latencyTarget: 200,
    disasterTime: 20,
    narrative: {
      title: "Scenario: Stripe's Payment Pipeline",
      description: "You're building a payment system. Every transaction MUST be processed exactly once — a double charge loses customers, a missed charge loses revenue. Your payment workers are slow (bank API calls take 2-5 seconds), and the primary database just failed during peak traffic.",
      objective: 'Process 12,000 payment requests/sec surviving a database failure, with no overloaded servers.',
      hint: 'Queue payments for async processing. Add replicas and health checks for the database so payments survive failures.',
    },
    unlockedComponents: ['trafficSource', 'server', 'database', 'loadBalancer', 'cache', 'messageQueue', 'worker', 'replica', 'healthCheck', 'circuitBreaker'],
    initialNodes: [
      { id: 'traffic-1', type: 'trafficSource', position: { x: 50, y: 300 }, data: { label: 'Checkout Requests', rps: 0, region: 'default' } },
      { id: 'lb-1', type: 'loadBalancer', position: { x: 280, y: 300 }, data: { label: 'API Load Balancer', rps: 0, algorithm: 'round-robin', status: 'healthy' } },
      { id: 'server-1', type: 'server', position: { x: 500, y: 150 }, data: { label: 'Payment API 1', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'server-2', type: 'server', position: { x: 500, y: 450 }, data: { label: 'Payment API 2', rps: 0, capacity: 4000, status: 'healthy' } },
      { id: 'db-1', type: 'database', position: { x: 800, y: 300 }, data: { label: 'Payments DB', rps: 0, capacity: 5000, status: 'healthy', isPrimary: true } },
    ],
    initialEdges: [
      { id: 'e-t-lb', source: 'traffic-1', target: 'lb-1', animated: true },
      { id: 'e-lb-s1', source: 'lb-1', target: 'server-1', animated: true },
      { id: 'e-lb-s2', source: 'lb-1', target: 'server-2', animated: true },
      { id: 'e-s1-db', source: 'server-1', target: 'db-1', animated: true },
      { id: 'e-s2-db', source: 'server-2', target: 'db-1', animated: true },
    ],
    winCondition: (metrics) => metrics.rps >= 12000 && metrics.overloadedServers === 0 && (metrics.survivedDisaster || true),
    failCondition: (metrics, tickCount) => {
      if (metrics.systemDown) return true;
      if (tickCount > 30 && metrics.overloadedServers > 1) return true;
      return false;
    },
    failMessage: 'Payment system down! Transactions are being lost.',
    failExplanation: "Without redundancy and async processing, a database failure during peak traffic means lost payments. Stripe uses idempotency keys, message queues, and database replicas to ensure every payment is processed exactly once.",
    winLesson: "Stripe processes billions in payments using idempotency keys (preventing double charges), async job queues (decoupling API from bank calls), and multi-region database replication. No single failure can lose a transaction.",
    references: [
      { title: 'Stripe Idempotency Keys', url: 'https://stripe.com/docs/api/idempotent_requests' },
      { title: "How Stripe Achieves Five 9s of Availability", url: 'https://www.youtube.com/watch?v=7vn49exuYxo' },
    ],
    nodeCosts: { server: 400, loadBalancer: 400, database: 500, cache: 500, messageQueue: 600, worker: 350, replica: 700, healthCheck: 300, circuitBreaker: 800 },
    activeSimulators: ['traffic', 'loadBalancer', 'queue', 'failover'],
    idealSolution: {
      description: 'Idempotent processing with exactly-once semantics',
      nodes: [
        { type: 'trafficSource', label: 'Merchants', count: 1 },
        { type: 'apiGateway', label: 'API Gateway', count: 1 },
        { type: 'server', label: 'Payment Server', count: 3 },
        { type: 'messageQueue', label: 'Transaction Queue', count: 1 },
        { type: 'worker', label: 'Settlement Worker', count: 2 },
        { type: 'database', label: 'Ledger DB', count: 1 },
        { type: 'cache', label: 'Idempotency Cache', count: 1 },
      ],
      explanation: 'API Gateway assigns idempotency keys. Payment servers check the cache before processing. Queue ensures settlement happens exactly once, even on retries.',
    },
  },
};

export const TOTAL_LEVELS = Object.keys(LEVEL_CONFIGS).filter(k => k !== '0').length;
